apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  creationTimestamp: '2021-09-28T15:49:05Z'
  generation: 1
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:params': {}
          'f:resources': {}
          'f:tasks': {}
      manager: Mozilla
      operation: Update
      time: '2021-09-28T15:49:05Z'
  name: acecicd-pipeline-deploy
  namespace: default
  resourceVersion: '161542'
  uid: a72f6fe3-ceb3-45ae-958e-ade35d742d40
spec:
  params:
    - default: default
      description: name of the namespace to deploy and to build image url
      name: namespace
      type: string
    - default: ace-demo
      description: name of the image in the registry
      name: image_name
      type: string
    - default: '1.0'
      description: image tag in the registry
      name: image_tag
      type: string
  resources:
    - name: image
      type: image
  tasks:
    - name: deploy-image
      params:
        - name: namespace
          value: $(params.namespace)
        - name: image_name
          value: $(params.image_name)
        - name: image_tag
          value: $(params.image_tag)
        - name: integrationServerName
          value: $(params.image_name)-$(params.image_tag)
      resources:
        inputs:
          - name: image
            resource: image
      taskRef:
        kind: Task
        name: task-deploy-aceimg
