apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: '2021-09-28T15:43:54Z'
  generation: 1
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:params': {}
          'f:resources':
            .: {}
            'f:inputs': {}
          'f:results': {}
          'f:steps': {}
          'f:volumes': {}
      manager: Mozilla
      operation: Update
      time: '2021-09-28T15:43:54Z'
  name: task-dockerf-build-push
  namespace: default
  resourceVersion: '156449'
  uid: 457e8bdb-079a-4db1-8abd-2bf91083e93d
spec:
  params:
    - default: registry.redhat.io/rhel8/buildah
      description: The location of the buildah builder image.
      name: BUILDER_IMAGE
      type: string
    - default: ./Dockerfile
      description: Path to the Dockerfile to build.
      name: DOCKERFILE
      type: string
    - default: 'false'
      description: Verify the TLS on the registry endpoint
      name: TLSVERIFY
      type: string
    - default: default
      description: namespace used to build the image url
      name: namespace
      type: string
  resources:
    inputs:
      - name: source
        type: git
      - name: image
        type: image
  results:
    - description: tag from git acecfg for image
      name: image_tag
    - description: name from git acecfg for image
      name: image_name
  steps:
    - image: $(params.BUILDER_IMAGE)
      name: build
      resources: {}
      script: |
        ls ./bars
        . ./imgcfg
        buildah bud --storage-driver=vfs --format=oci \
          --tls-verify=$(params.TLSVERIFY) --layers \
          -f $(params.DOCKERFILE) -t $(resources.inputs.image.url)/$(params.namespace)/$imgname:$imgtag .
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
      workingDir: /workspace/source
    - image: $(params.BUILDER_IMAGE)
      name: push
      resources: {}
      script: |
        . ./imgcfg
        buildah push --storage-driver=vfs --tls-verify=$(params.TLSVERIFY) \
          $(resources.inputs.image.url)/$(params.namespace)/$imgname:$imgtag \
          'docker://$(resources.inputs.image.url)/$(params.namespace)/'$imgname:$imgtag
        echo -n $imgtag > /tekton/results/image_tag
        echo -n $imgname > /tekton/results/image_name
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
      workingDir: /workspace/source
  volumes:
    - emptyDir: {}
      name: varlibcontainers
