apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: '2021-09-28T15:46:59Z'
  generation: 4
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:params': {}
          'f:resources':
            .: {}
            'f:inputs': {}
          'f:steps': {}
      manager: Mozilla
      operation: Update
      time: '2021-09-28T15:46:59Z'
  name: task-deploy-aceimg
  namespace: default
  resourceVersion: '650269'
  uid: 6da1ab07-e3f3-47c6-9b91-dd09432cf14b
spec:
  params:
    - default: default
      description: release namespace
      name: namespace
      type: string
    - description: name of the integration server
      name: integrationServerName
      type: string
    - description: image tag name
      name: image_tag
      type: string
    - description: image name
      name: image_name
      type: string
    - default: L-APEH-C49KZH
      description: license number
      name: license
      type: string
    - default: tracing
      description: namespace where OD is installed
      name: tracing_ns
      type: string
    - default: 'false'
      description: enable tracing
      name: tracing_enabled
      type: string
    - default: 12.0.1.0-r4
      description: fully qualified ace version
      name: ace_version
      type: string
  resources:
    inputs:
      - name: image
        type: image
  steps:
    - image: 'quay.io/openshift/origin-cli:latest'
      name: oc
      resources: {}
      script: |
        ISNAME=$(echo "$(params.integrationServerName)" | tr -d .)
        cat << EOF > integrationserver.yaml
        apiVersion: appconnect.ibm.com/v1beta1
        kind: IntegrationServer
        metadata:
          name: $ISNAME
          namespace: $(params.namespace)
        spec:
          pod:
           containers:
             runtime:
               image: $(resources.inputs.image.url)/$(params.namespace)/$(params.image_name):$(params.image_tag)
          configurations: []
          designerFlowsOperationMode: disabled
          license:
            accept: true
            license: $(params.license)
            use: CloudPakForIntegrationNonProduction
          replicas: 1
          router:
            timeout: 120s
          service:
            endpointType: http
          useCommonServices: true
          tracing:
            enabled: $(params.tracing_enabled)
            namespace: $(params.tracing_ns)
          version: $(params.ace_version)
        EOF
        cat integrationserver.yaml
        oc apply -f integrationserver.yaml
